name: mmSupernaturals
main: me.matterz.supernaturals.SupernaturalsPlugin
version: 1.4.1
author: Matterz, edited by mmiillkkaa
commands:
  sn:
    description: Supernatural commands
    usage: /<command> - lists commands
